import numpy as np


def generate_group_column(group_spec: dict, sample_generator: callable, shuffle: bool = False) -> np.ndarray:
    """
    Generates a list of values based on group specifications and a sample generator function.
    Args:
      group_spec (dict): A dictionary where keys represent group sizes (int) and values represent
                 the frequency (int) of those group sizes.
      sample_generator (callable): A function that generates a single sample value.
      shuffle (bool, optional): If True, shuffles the resulting array. Defaults to False.

    Returns:
      np.ndarray: An array of values where each group of values is repeated according to the group size
          and the number of groups is determined by the frequency in `group_spec`.

    Example:
      group_spec = {2: 3, 3: 2}
      sample_generator = lambda: random.randint(1, 100)
      generate_group_column(group_spec, sample_generator)
      # Output: [val1, val1, val2, val2, val3, val3, val4, val4, val4, val5, val5, val5]
      # (where val1, val2, ..., val5 are generated by sample_generator)
    """
    values = []

    for group_size, freq in group_spec.items():
        for _ in range(freq):
            group_val = sample_generator()
            values.extend([group_val] * group_size)
            
    values = np.array(values)
    
    if (shuffle):
      np.random.shuffle(values)
      
    return values


def generate_numeric_column(rows: int, col_params: dict) -> np.ndarray:
    """
    Generates a numeric column based on the specified parameters.
    Args:
      rows (int): The number of rows to generate.
      col_params (dict): A dictionary containing the parameters for column generation.
        - "min" (int or float): The minimum value for the generated data.
        - "max" (int or float): The maximum value for the generated data.
        - "distribution" (str): The type of distribution to use. Supported values are:
          - "uniform": Uniform distribution.
          - "normal": Normal distribution.
          - "zipf": Zipfian distribution.
          - "constant": Constant value.
        - "mode" (str): The mode of the generated values. Supported values are:
          - "discrete": Generates integer values.
          - "continuous": Generates floating-point values.
        - Additional keys depending on the distribution:
          - For "normal":
            - "mean" (float): The mean of the normal distribution.
            - "std" (float): The standard deviation of the normal distribution.
          - For "zipf":
            - "skewness" (float): The skewness of the Zipf distribution.
          - For "constant":
            - "value" (int or float): The constant value to fill the column.
            
    Returns:
      np.ndarray: An array containing the generated numeric values.
    """
    min_val = col_params["min"]
    max_val = col_params["max"]
    distribution = col_params["distribution"]
    mode = col_params["mode"]

    if distribution == "uniform":
        if mode == "discrete":
            values = np.random.randint(min_val, max_val + 1, size=rows)
        else:
            values = np.random.uniform(min_val, max_val, size=rows)
            values = np.round(values, 2)
            
    elif distribution == "normal":
        mean = col_params["mean"]
        std = col_params["std"]
        values = np.random.normal(mean, std, size=rows)
        values = np.clip(values, min_val, max_val)
        if mode == "discrete":
            values = np.round(values).astype(int)
        else:
            values = np.round(values, 2)
            
    elif distribution == "zipf":
        skewness = col_params["skewness"]
        values = np.random.zipf(skewness, size=rows)
        values = values[(values >= min_val) & (values <= max_val)]
        while len(values) < rows:
            more = np.random.zipf(skewness, size=rows - len(values))
            more = more[(more >= min_val) & (more <= max_val)]
            values = np.concatenate([values, more])
        values = values[:rows]
            
    elif distribution == "constant":
        value = col_params["value"]
        values = np.full(rows, value)
        if mode != "discrete":
            values = np.round(values.astype(float), 2)
            
    else:
        raise ValueError(f"Unsupported distribution type: {distribution}")

    return values


def generate_categorical_column(rows: int, col_params: dict) -> np.ndarray:
    """
    Generate a categorical column based on the specified parameters.
    Parameters:
      rows (int): The number of rows (values) to generate.
      col_params (dict): A dictionary containing the parameters for the column generation:
        - "num_categories" (int): The number of distinct categories.
        - "distribution" (str): The type of distribution to use. Supported values are:
          - "uniform": Categories are chosen with equal probability.
          - "normal": Categories are chosen based on a normal distribution.
          - "constant": All values are the same.
        - "categories" (list): A list of category labels. The length must match "num_categories".
        - "std" (float, optional): The standard deviation for the normal distribution. Required if "distribution" is "normal".
        - "value" (any, optional): The constant value to use if "distribution" is "constant".
        
    Returns:
      np.ndarray: An array of generated categorical values.
    """
    num_categories = col_params["num_categories"]
    distribution = col_params["distribution"]
    categories = col_params["categories"]

    if len(categories) != num_categories:
        raise ValueError("Length of 'categories' list must match 'num_categories'")

    if distribution == "uniform":
        return np.random.choice(categories, size=rows)
      
    elif distribution == "normal":
        indices = np.arange(num_categories)
        center = (num_categories - 1) / 2
        std = col_params.get("std")

        probs = np.exp(-0.5 * ((indices - center) / std) ** 2)
        probs /= probs.sum()  # normalize to sum to 1

        return np.random.choice(categories, size=rows, p=probs)
      
    elif distribution == "constant":
        value = col_params["value"]
        return np.full(rows, value)
      
    else:
        raise ValueError(f"Unsupported distribution type: {distribution}")
